ARG IMAGE_BASE
FROM registry.opensuse.org/opensuse/tumbleweed:20260615 AS build

RUN zypper install -y make

RUN mkdir /home/build

# Build (really, just arrange files of) foomuuri from submodule
COPY foomuuri /home/build/foomuuri
WORKDIR /home/build/foomuuri
RUN make install DESTDIR=/output

FROM ${IMAGE_BASE}/base

# Install stuff built from source
COPY --from=build /output /
RUN systemctl enable foomuuri

# Install a bunch of software
# additional networking troubleshooting utils
# foomuuri deps
# container runtime
# shell stuff
# misc admin tools
# SSH server
# disk partitioning tools
RUN zypper install -y \
    iputils traceroute mtr bind-utils tcpdump netcat-openbsd nftables \
    python314 \
    podman \
    bash-completion jq less \
    nano htop ncdu \
    openssh-server \
    util-linux parted growpart
RUN systemctl enable sshd

COPY images/server-base/config/. /

# Rearrange disk layout for ostree
RUN rm -rf /boot /home /root /usr/local /srv /opt /mnt /var /usr/lib/sysimage/rpm
RUN mkdir -p /sysroot /boot /usr/lib/ostree /var
RUN ln -sT sysroot/ostree /ostree \
    && ln -sT var/roothome /root \
    && ln -sT var/srv /srv \
    && ln -sT var/opt /opt \
    && ln -sT var/mnt /mnt \
    && ln -sT var/home /home \
    && ln -sT ../var/usrlocal /usr/local
RUN echo "HOME=/var/home" | tee -a "/etc/default/useradd"
# Rescue select configs from /usr/etc
RUN cp -R /usr/etc/ssh /etc && rm -r /usr/etc

RUN bootc container lint