zone {
  localhost
  podman podman*
  nebula tun*
  public enp*
}

# Accept incoming traffic with only select protocols
public-localhost {
  dhcp-client
  dhcpv6-client
  ping
  ssh
  udp 4242 # Nebula host
  udp 32768-60999  # Nebula containers, TODO restrict
  drop log
}

# Allow all egress from host by default
localhost-public {
  accept
}

# Allow all egress from containers with podman bridge
# (only very few containers will have it, rest use Nebula)
podman-public {
  accept
}
# aardvark-dns would use bridge gateway, but it is unused
public-podman {
  http
  https
  drop log
}

# Let Nebula do its own firewalling
nebula-localhost {
  accept
}
localhost-nebula {
  accept
}