# Permit root login, but never with password
PasswordAuthentication no
PermitRootLogin prohibit-password

# For root, also load authorized keys from image-provided file (empty in this base image)
Match User root
    AuthorizedKeysFile .ssh/authorized_keys /etc/ssh/image_authorized_keys
